### ISSUE TITLE
[BetterDashless] emojis in channel names are reformatted as text

### ISSUE THREAD

**Issue by solonovamax** [MrAn0nym/Aliucord-Plugins#1]
Emojis in channel names are reformatted as their corresponding text names.

This does not always occur and I cannot figure out how to trigger it again.

While attempting to create a bug report, I disabled the plugin and upon re-enabling it, the issue is gone.

I'm on mobile so I cannot upload a picture, but I will update with an example when I can trigger it again.

**Comment by MrAn0nym** [comment]
Should be fixed now ^^

**Comment by solonovamax** [comment]
It doesn't seem fixed to me.

I still see this issue in the latest version, 1.0.2

**Comment by MrAn0nym** [comment]
apparently the fix broke again. For now you can just disable twemoji in channel names until Aliucord finally gets a good way to change the plugin load order
